[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Tiny-DiscordBot"
description = "A lightweight Discord bot framework"
readme = "README.md"
